# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createSweepSurfaceForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(299, 388)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.uiOk = QtWidgets.QPushButton(Form)
        self.uiOk.setObjectName("uiOk")
        self.gridLayout_4.addWidget(self.uiOk, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.uiPathLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.uiPathLineEdit.setReadOnly(True)
        self.uiPathLineEdit.setObjectName("uiPathLineEdit")
        self.gridLayout.addWidget(self.uiPathLineEdit, 0, 1, 1, 1)
        self.uiSelectPathButton = QtWidgets.QPushButton(self.groupBox)
        self.uiSelectPathButton.setObjectName("uiSelectPathButton")
        self.gridLayout.addWidget(self.uiSelectPathButton, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.uiPreview = QtWidgets.QPushButton(Form)
        self.uiPreview.setObjectName("uiPreview")
        self.gridLayout_4.addWidget(self.uiPreview, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.uiLastSectionLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.uiLastSectionLineEdit.setObjectName("uiLastSectionLineEdit")
        self.gridLayout_2.addWidget(self.uiLastSectionLineEdit, 6, 0, 1, 1)
        self.uiRadiusSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.uiRadiusSpinBox.setMinimum(50)
        self.uiRadiusSpinBox.setMaximum(500)
        self.uiRadiusSpinBox.setSingleStep(50)
        self.uiRadiusSpinBox.setObjectName("uiRadiusSpinBox")
        self.gridLayout_2.addWidget(self.uiRadiusSpinBox, 1, 1, 1, 1)
        self.uiConstantSectionRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.uiConstantSectionRadioButton.setObjectName("uiConstantSectionRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.uiConstantSectionRadioButton)
        self.gridLayout_2.addWidget(self.uiConstantSectionRadioButton, 2, 0, 1, 1)
        self.uiSelectConstantSectionButton = QtWidgets.QPushButton(self.groupBox_2)
        self.uiSelectConstantSectionButton.setObjectName("uiSelectConstantSectionButton")
        self.gridLayout_2.addWidget(self.uiSelectConstantSectionButton, 3, 1, 1, 1)
        self.uiSelectFirstSectionButton = QtWidgets.QPushButton(self.groupBox_2)
        self.uiSelectFirstSectionButton.setObjectName("uiSelectFirstSectionButton")
        self.gridLayout_2.addWidget(self.uiSelectFirstSectionButton, 5, 1, 1, 1)
        self.uiSelectLastSectionButton = QtWidgets.QPushButton(self.groupBox_2)
        self.uiSelectLastSectionButton.setObjectName("uiSelectLastSectionButton")
        self.gridLayout_2.addWidget(self.uiSelectLastSectionButton, 6, 1, 1, 1)
        self.uiConstantSectionLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.uiConstantSectionLineEdit.setObjectName("uiConstantSectionLineEdit")
        self.gridLayout_2.addWidget(self.uiConstantSectionLineEdit, 3, 0, 1, 1)
        self.uiEvolvingSectionRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.uiEvolvingSectionRadioButton.setObjectName("uiEvolvingSectionRadioButton")
        self.buttonGroup.addButton(self.uiEvolvingSectionRadioButton)
        self.gridLayout_2.addWidget(self.uiEvolvingSectionRadioButton, 4, 0, 1, 1)
        self.uiFirstSectionLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.uiFirstSectionLineEdit.setObjectName("uiFirstSectionLineEdit")
        self.gridLayout_2.addWidget(self.uiFirstSectionLineEdit, 5, 0, 1, 1)
        self.uiRadiusLabel = QtWidgets.QLabel(self.groupBox_2)
        self.uiRadiusLabel.setObjectName("uiRadiusLabel")
        self.gridLayout_2.addWidget(self.uiRadiusLabel, 1, 0, 1, 1)
        self.uiCircularRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.uiCircularRadioButton.setChecked(True)
        self.uiCircularRadioButton.setObjectName("uiCircularRadioButton")
        self.buttonGroup.addButton(self.uiCircularRadioButton)
        self.gridLayout_2.addWidget(self.uiCircularRadioButton, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.uiOk.setText(_translate("Form", "Ok"))
        self.groupBox.setTitle(_translate("Form", "Path"))
        self.uiSelectPathButton.setToolTip(_translate("Form", "Select a path"))
        self.uiSelectPathButton.setText(_translate("Form", "Select"))
        self.uiPreview.setText(_translate("Form", "Preview"))
        self.groupBox_2.setTitle(_translate("Form", "Section"))
        self.uiConstantSectionRadioButton.setText(_translate("Form", "Constant Section"))
        self.uiSelectConstantSectionButton.setToolTip(_translate("Form", "Select a constant cross section"))
        self.uiSelectConstantSectionButton.setText(_translate("Form", "Select"))
        self.uiSelectFirstSectionButton.setToolTip(_translate("Form", "Select an inital cross section"))
        self.uiSelectFirstSectionButton.setText(_translate("Form", "Select"))
        self.uiSelectLastSectionButton.setToolTip(_translate("Form", "Select an end cross section"))
        self.uiSelectLastSectionButton.setText(_translate("Form", "Select"))
        self.uiEvolvingSectionRadioButton.setText(_translate("Form", "Evolving Section"))
        self.uiRadiusLabel.setText(_translate("Form", "Radius:"))
        self.uiCircularRadioButton.setText(_translate("Form", "Circular"))
