# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sketchProperty.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SketchProperty(object):
    def setupUi(self, SketchProperty):
        SketchProperty.setObjectName("SketchProperty")
        SketchProperty.resize(270, 325)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SketchProperty)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.TextLabelID = QtWidgets.QLabel(SketchProperty)
        self.TextLabelID.setObjectName("TextLabelID")
        self.horizontalLayout_6.addWidget(self.TextLabelID)
        self.LineEditID = QtWidgets.QLineEdit(SketchProperty)
        self.LineEditID.setReadOnly(True)
        self.LineEditID.setObjectName("LineEditID")
        self.horizontalLayout_6.addWidget(self.LineEditID)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(SketchProperty)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.TextLabelPoint1 = QtWidgets.QLabel(self.groupBox)
        self.TextLabelPoint1.setObjectName("TextLabelPoint1")
        self.horizontalLayout_5.addWidget(self.TextLabelPoint1)
        self.LineEditPoint1 = QtWidgets.QLineEdit(self.groupBox)
        self.LineEditPoint1.setObjectName("LineEditPoint1")
        self.horizontalLayout_5.addWidget(self.LineEditPoint1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(SketchProperty)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TextLabelColor = QtWidgets.QLabel(self.groupBox_2)
        self.TextLabelColor.setObjectName("TextLabelColor")
        self.horizontalLayout.addWidget(self.TextLabelColor)
        self.ComboBoxColor = QtWidgets.QComboBox(self.groupBox_2)
        self.ComboBoxColor.setObjectName("ComboBoxColor")
        self.ComboBoxColor.addItem("")
        self.ComboBoxColor.addItem("")
        self.ComboBoxColor.addItem("")
        self.ComboBoxColor.addItem("")
        self.ComboBoxColor.addItem("")
        self.horizontalLayout.addWidget(self.ComboBoxColor)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TextLabelType = QtWidgets.QLabel(self.groupBox_2)
        self.TextLabelType.setObjectName("TextLabelType")
        self.horizontalLayout_2.addWidget(self.TextLabelType)
        self.ComboBoxType = QtWidgets.QComboBox(self.groupBox_2)
        self.ComboBoxType.setObjectName("ComboBoxType")
        self.ComboBoxType.addItem("")
        self.ComboBoxType.addItem("")
        self.horizontalLayout_2.addWidget(self.ComboBoxType)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TextLabelStyle = QtWidgets.QLabel(self.groupBox_2)
        self.TextLabelStyle.setObjectName("TextLabelStyle")
        self.horizontalLayout_3.addWidget(self.TextLabelStyle)
        self.ComboBoxStyle = QtWidgets.QComboBox(self.groupBox_2)
        self.ComboBoxStyle.setObjectName("ComboBoxStyle")
        self.ComboBoxStyle.addItem("")
        self.ComboBoxStyle.addItem("")
        self.ComboBoxStyle.addItem("")
        self.ComboBoxStyle.addItem("")
        self.horizontalLayout_3.addWidget(self.ComboBoxStyle)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TextLabelWidth = QtWidgets.QLabel(self.groupBox_2)
        self.TextLabelWidth.setObjectName("TextLabelWidth")
        self.horizontalLayout_4.addWidget(self.TextLabelWidth)
        self.ComboBoxWidth = QtWidgets.QComboBox(self.groupBox_2)
        self.ComboBoxWidth.setObjectName("ComboBoxWidth")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.ComboBoxWidth.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBoxWidth)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PushButtonOK = QtWidgets.QPushButton(SketchProperty)
        self.PushButtonOK.setObjectName("PushButtonOK")
        self.horizontalLayout_7.addWidget(self.PushButtonOK)
        self.PushButtonCancel = QtWidgets.QPushButton(SketchProperty)
        self.PushButtonCancel.setObjectName("PushButtonCancel")
        self.horizontalLayout_7.addWidget(self.PushButtonCancel)
        self.PushButtonApply = QtWidgets.QPushButton(SketchProperty)
        self.PushButtonApply.setObjectName("PushButtonApply")
        self.horizontalLayout_7.addWidget(self.PushButtonApply)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)

        self.retranslateUi(SketchProperty)
        QtCore.QMetaObject.connectSlotsByName(SketchProperty)

    def retranslateUi(self, SketchProperty):
        _translate = QtCore.QCoreApplication.translate
        SketchProperty.setWindowTitle(_translate("SketchProperty", "Form"))
        self.TextLabelID.setText(_translate("SketchProperty", "ID"))
        self.groupBox.setTitle(_translate("SketchProperty", "Geometry Properties"))
        self.TextLabelPoint1.setText(_translate("SketchProperty", "Point"))
        self.groupBox_2.setTitle(_translate("SketchProperty", "Attributes"))
        self.TextLabelColor.setText(_translate("SketchProperty", "Color"))
        self.ComboBoxColor.setItemText(0, _translate("SketchProperty", "BLACK"))
        self.ComboBoxColor.setItemText(1, _translate("SketchProperty", "BROWN"))
        self.ComboBoxColor.setItemText(2, _translate("SketchProperty", "RED"))
        self.ComboBoxColor.setItemText(3, _translate("SketchProperty", "ORANGE"))
        self.ComboBoxColor.setItemText(4, _translate("SketchProperty", "YELLOW"))
        self.TextLabelType.setText(_translate("SketchProperty", "Type"))
        self.ComboBoxType.setItemText(0, _translate("SketchProperty", "Main"))
        self.ComboBoxType.setItemText(1, _translate("SketchProperty", "Auxiliary"))
        self.TextLabelStyle.setText(_translate("SketchProperty", "Style"))
        self.ComboBoxStyle.setItemText(0, _translate("SketchProperty", "SOLID"))
        self.ComboBoxStyle.setItemText(1, _translate("SketchProperty", "DASH"))
        self.ComboBoxStyle.setItemText(2, _translate("SketchProperty", "DOT"))
        self.ComboBoxStyle.setItemText(3, _translate("SketchProperty", "DOTDASH"))
        self.TextLabelWidth.setText(_translate("SketchProperty", "Width"))
        self.ComboBoxWidth.setItemText(0, _translate("SketchProperty", "1.0"))
        self.ComboBoxWidth.setItemText(1, _translate("SketchProperty", "2.0"))
        self.ComboBoxWidth.setItemText(2, _translate("SketchProperty", "3.0"))
        self.ComboBoxWidth.setItemText(3, _translate("SketchProperty", "4.0"))
        self.ComboBoxWidth.setItemText(4, _translate("SketchProperty", "5.0"))
        self.ComboBoxWidth.setItemText(5, _translate("SketchProperty", "6.0"))
        self.ComboBoxWidth.setItemText(6, _translate("SketchProperty", "7.0"))
        self.ComboBoxWidth.setItemText(7, _translate("SketchProperty", "8.0"))
        self.ComboBoxWidth.setItemText(8, _translate("SketchProperty", "9.0"))
        self.PushButtonOK.setText(_translate("SketchProperty", "Ok"))
        self.PushButtonCancel.setText(_translate("SketchProperty", "Cancel"))
        self.PushButtonApply.setText(_translate("SketchProperty", "Apply"))
